// Code generated by ent, DO NOT EDIT.

package medias

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the medias type in the database.
	Label = "medias"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOid holds the string denoting the oid field in the database.
	FieldOid = "oid"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// Table holds the table name of the medias in the database.
	Table = "medias"
)

// Columns holds all SQL columns for medias fields.
var Columns = []string{
	FieldID,
	FieldOid,
	FieldPath,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Medias queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOid orders the results by the oid field.
func ByOid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOid, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}
