// Code generated by ent, DO NOT EDIT.

package ent

import (
	"erm/internal/db/ent/medias"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Medias is the model entity for the Medias schema.
type Medias struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Oid holds the value of the "oid" field.
	Oid string `json:"oid,omitempty"`
	// Path holds the value of the "path" field.
	Path         string `json:"path,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Medias) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case medias.FieldID:
			values[i] = new(sql.NullInt64)
		case medias.FieldOid, medias.FieldPath:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Medias fields.
func (m *Medias) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case medias.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int(value.Int64)
		case medias.FieldOid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oid", values[i])
			} else if value.Valid {
				m.Oid = value.String
			}
		case medias.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				m.Path = value.String
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Medias.
// This includes values selected through modifiers, order, etc.
func (m *Medias) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// Update returns a builder for updating this Medias.
// Note that you need to call Medias.Unwrap() before calling this method if this Medias
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Medias) Update() *MediasUpdateOne {
	return NewMediasClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Medias entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Medias) Unwrap() *Medias {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Medias is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Medias) String() string {
	var builder strings.Builder
	builder.WriteString("Medias(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("oid=")
	builder.WriteString(m.Oid)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(m.Path)
	builder.WriteByte(')')
	return builder.String()
}

// MediasSlice is a parsable slice of Medias.
type MediasSlice []*Medias
