// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"erm/internal/db/ent/medias"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediasCreate is the builder for creating a Medias entity.
type MediasCreate struct {
	config
	mutation *MediasMutation
	hooks    []Hook
}

// SetOid sets the "oid" field.
func (mc *MediasCreate) SetOid(s string) *MediasCreate {
	mc.mutation.SetOid(s)
	return mc
}

// SetPath sets the "path" field.
func (mc *MediasCreate) SetPath(s string) *MediasCreate {
	mc.mutation.SetPath(s)
	return mc
}

// Mutation returns the MediasMutation object of the builder.
func (mc *MediasCreate) Mutation() *MediasMutation {
	return mc.mutation
}

// Save creates the Medias in the database.
func (mc *MediasCreate) Save(ctx context.Context) (*Medias, error) {
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MediasCreate) SaveX(ctx context.Context) *Medias {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MediasCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MediasCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MediasCreate) check() error {
	if _, ok := mc.mutation.Oid(); !ok {
		return &ValidationError{Name: "oid", err: errors.New(`ent: missing required field "Medias.oid"`)}
	}
	if _, ok := mc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Medias.path"`)}
	}
	return nil
}

func (mc *MediasCreate) sqlSave(ctx context.Context) (*Medias, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MediasCreate) createSpec() (*Medias, *sqlgraph.CreateSpec) {
	var (
		_node = &Medias{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(medias.Table, sqlgraph.NewFieldSpec(medias.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.Oid(); ok {
		_spec.SetField(medias.FieldOid, field.TypeString, value)
		_node.Oid = value
	}
	if value, ok := mc.mutation.Path(); ok {
		_spec.SetField(medias.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	return _node, _spec
}

// MediasCreateBulk is the builder for creating many Medias entities in bulk.
type MediasCreateBulk struct {
	config
	builders []*MediasCreate
}

// Save creates the Medias entities in the database.
func (mcb *MediasCreateBulk) Save(ctx context.Context) ([]*Medias, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Medias, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MediasCreateBulk) SaveX(ctx context.Context) []*Medias {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MediasCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MediasCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
