// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"erm/internal/db/ent/predicate"
	"erm/internal/db/ent/userlogins"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserloginsUpdate is the builder for updating Userlogins entities.
type UserloginsUpdate struct {
	config
	hooks    []Hook
	mutation *UserloginsMutation
}

// Where appends a list predicates to the UserloginsUpdate builder.
func (uu *UserloginsUpdate) Where(ps ...predicate.Userlogins) *UserloginsUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUsername sets the "username" field.
func (uu *UserloginsUpdate) SetUsername(s string) *UserloginsUpdate {
	uu.mutation.SetUsername(s)
	return uu
}

// SetPassword sets the "password" field.
func (uu *UserloginsUpdate) SetPassword(s string) *UserloginsUpdate {
	uu.mutation.SetPassword(s)
	return uu
}

// Mutation returns the UserloginsMutation object of the builder.
func (uu *UserloginsUpdate) Mutation() *UserloginsMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserloginsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserloginsUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserloginsUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserloginsUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserloginsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userlogins.Table, userlogins.Columns, sqlgraph.NewFieldSpec(userlogins.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Username(); ok {
		_spec.SetField(userlogins.FieldUsername, field.TypeString, value)
	}
	if value, ok := uu.mutation.Password(); ok {
		_spec.SetField(userlogins.FieldPassword, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlogins.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserloginsUpdateOne is the builder for updating a single Userlogins entity.
type UserloginsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserloginsMutation
}

// SetUsername sets the "username" field.
func (uuo *UserloginsUpdateOne) SetUsername(s string) *UserloginsUpdateOne {
	uuo.mutation.SetUsername(s)
	return uuo
}

// SetPassword sets the "password" field.
func (uuo *UserloginsUpdateOne) SetPassword(s string) *UserloginsUpdateOne {
	uuo.mutation.SetPassword(s)
	return uuo
}

// Mutation returns the UserloginsMutation object of the builder.
func (uuo *UserloginsUpdateOne) Mutation() *UserloginsMutation {
	return uuo.mutation
}

// Where appends a list predicates to the UserloginsUpdate builder.
func (uuo *UserloginsUpdateOne) Where(ps ...predicate.Userlogins) *UserloginsUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserloginsUpdateOne) Select(field string, fields ...string) *UserloginsUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated Userlogins entity.
func (uuo *UserloginsUpdateOne) Save(ctx context.Context) (*Userlogins, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserloginsUpdateOne) SaveX(ctx context.Context) *Userlogins {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserloginsUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserloginsUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserloginsUpdateOne) sqlSave(ctx context.Context) (_node *Userlogins, err error) {
	_spec := sqlgraph.NewUpdateSpec(userlogins.Table, userlogins.Columns, sqlgraph.NewFieldSpec(userlogins.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Userlogins.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userlogins.FieldID)
		for _, f := range fields {
			if !userlogins.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userlogins.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Username(); ok {
		_spec.SetField(userlogins.FieldUsername, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Password(); ok {
		_spec.SetField(userlogins.FieldPassword, field.TypeString, value)
	}
	_node = &Userlogins{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlogins.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
