// Code generated by ent, DO NOT EDIT.

package ent

import (
	"erm/internal/db/ent/userlogins"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Userlogins is the model entity for the Userlogins schema.
type Userlogins struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password     string `json:"password,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Userlogins) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userlogins.FieldID:
			values[i] = new(sql.NullInt64)
		case userlogins.FieldUsername, userlogins.FieldPassword:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Userlogins fields.
func (u *Userlogins) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userlogins.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case userlogins.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				u.Username = value.String
			}
		case userlogins.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				u.Password = value.String
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Userlogins.
// This includes values selected through modifiers, order, etc.
func (u *Userlogins) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// Update returns a builder for updating this Userlogins.
// Note that you need to call Userlogins.Unwrap() before calling this method if this Userlogins
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *Userlogins) Update() *UserloginsUpdateOne {
	return NewUserloginsClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the Userlogins entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *Userlogins) Unwrap() *Userlogins {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: Userlogins is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *Userlogins) String() string {
	var builder strings.Builder
	builder.WriteString("Userlogins(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("username=")
	builder.WriteString(u.Username)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(u.Password)
	builder.WriteByte(')')
	return builder.String()
}

// UserloginsSlice is a parsable slice of Userlogins.
type UserloginsSlice []*Userlogins
