// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Medias is the predicate function for medias builders.
type Medias func(*sql.Selector)

// Opinions is the predicate function for opinions builders.
type Opinions func(*sql.Selector)

// Userlogins is the predicate function for userlogins builders.
type Userlogins func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
