// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MediasColumns holds the columns for the "medias" table.
	MediasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "oid", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
	}
	// MediasTable holds the schema information for the "medias" table.
	MediasTable = &schema.Table{
		Name:       "medias",
		Columns:    MediasColumns,
		PrimaryKey: []*schema.Column{MediasColumns[0]},
	}
	// OpinionsColumns holds the columns for the "opinions" table.
	OpinionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "telephone", Type: field.TypeString},
		{Name: "time", Type: field.TypeTime},
		{Name: "brand", Type: field.TypeString},
		{Name: "resturtant", Type: field.TypeString},
		{Name: "outlook1", Type: field.TypeString},
		{Name: "outlook2", Type: field.TypeString},
		{Name: "outlook3", Type: field.TypeString},
		{Name: "waiting1", Type: field.TypeString},
		{Name: "waiting2", Type: field.TypeString},
		{Name: "ordering1", Type: field.TypeString},
		{Name: "ordering2", Type: field.TypeString},
		{Name: "ordering3", Type: field.TypeString},
		{Name: "service1", Type: field.TypeString},
		{Name: "service2", Type: field.TypeString},
		{Name: "service3", Type: field.TypeString},
		{Name: "qunility1", Type: field.TypeString},
		{Name: "qunility2", Type: field.TypeString},
		{Name: "qunility3", Type: field.TypeString},
		{Name: "value1", Type: field.TypeString},
		{Name: "value2", Type: field.TypeString},
		{Name: "comment", Type: field.TypeString},
		{Name: "rating", Type: field.TypeInt},
		{Name: "createdat", Type: field.TypeTime},
	}
	// OpinionsTable holds the schema information for the "opinions" table.
	OpinionsTable = &schema.Table{
		Name:       "opinions",
		Columns:    OpinionsColumns,
		PrimaryKey: []*schema.Column{OpinionsColumns[0]},
	}
	// UserloginsColumns holds the columns for the "userlogins" table.
	UserloginsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// UserloginsTable holds the schema information for the "userlogins" table.
	UserloginsTable = &schema.Table{
		Name:       "userlogins",
		Columns:    UserloginsColumns,
		PrimaryKey: []*schema.Column{UserloginsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "email", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "user_status", Type: field.TypeInt, Default: 0},
		{Name: "user_role", Type: field.TypeString, Default: "admin"},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "users_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MediasTable,
		OpinionsTable,
		UserloginsTable,
		UsersTable,
	}
)

func init() {
}
